spring:
  application:
    name: my-recipes-backend
  data:
    mongodb:
      uri: mongodb://recipe-usr:recipe-pwd@mongodb/myrecipes-db     
  cloud:
    config:
      uri: http://config:8888
      fail-fast: true
      password: my-recipes-backend
      username: user

security:
  basic:
    enabled: false

management:
  security:
    enabled:false

#